### ISSUE TITLE
Image tag unsupported

### ISSUE THREAD

**Issue by zauberparacelsus** [dcwatson/bbcode#2]
The parser does not appear to support the [img] bbcode tag.  Like the other issue I reported, I'll need to code around it.

**Comment by dzpt** [comment]
@homeworkprod it won't work with url has double dash.

https://domain/suzuki-swace-2020-3--1600832941-width1004height565-auto-crop.jpg
->
https://domain/suzuki-swace-2020-3&ndash;1600832941-width1004height565-auto-crop.jpg

**Comment by dzpt** [comment]
Its needed to have `replace_cosmetic=False` to prevent conversion -- to `&ndash;`

**Comment by homeworkprod** [comment]
@dzpt, that is correct. That's why I have [disabled it for image tags](https://github.com/byceps/byceps/blob/6ba16b966e0fa3a401dd991213f07c97b332d72c/byceps/services/text_markup/service.py#L56) and code blocks, but also [in general](https://github.com/byceps/byceps/blob/6ba16b966e0fa3a401dd991213f07c97b332d72c/byceps/services/text_markup/service.py#L29) (probably because I'd rather give up on nicer typography in "user-generated content" in favor of avoiding unexpected surprises).

I also have [tests in place](https://github.com/byceps/byceps/blob/6ba16b966e0fa3a401dd991213f07c97b332d72c/tests/unit/services/text_markup/test_service.py).

Thanks for mentioning that specific example, though; I've added a case that specifically checks that URLs are not changed regarding cosmetic replacements.
